// heights.js — every battle figure's canon height in cm, per era (p1 = Part I, p2 = Shippuden),
// measured from the soles to the top of the skull. js/core/stature.js turns it into the figure's size.
//   source: "databook"  the official databooks, as the character's Narutopedia infobox gives them
//           "anime"     an anime-only character's height from their Narutopedia infobox (no databook)
//           "estimate"  no canon height: a fitting guess (a clone is its original's height)
//   kind:   "human" | "beast" (a creature at about human scale; cm is its silhouette) | "giant" (one fixed size)
// A character with one figure only uses it for both eras. Where Narutopedia gives a Part I range,
// the end-of-Part-I figure is used (the note has the range). Compiled 2026-09-26.
export const HEIGHTS = {
  asuma: { kind: "human", p1: 190.8, p2: 190.8, source: "databook", note: "Narutopedia: only Part I 190.8 cm; used for both eras" },
  ay: { kind: "human", p2: 198.2, source: "databook", note: "Narutopedia: A (Fourth Raikage) Part II 198.2 cm" },
  chiyo: { kind: "human", p2: 149.1, source: "databook", note: "Narutopedia: Part II 149.1 cm" },
  choji: { kind: "human", p1: 156.3, p2: 172.3, source: "databook", note: "Narutopedia: Part I 150.6-156.3 cm (later used), Part II 172.3 cm" },
  chojuro: { kind: "human", p2: 163.6, source: "databook", note: "Narutopedia: Part II 163.6 cm" },
  darui: { kind: "human", p2: 176.5, source: "databook", note: "Narutopedia: Part II 176.5 cm" },
  deidara: { kind: "human", p2: 166, source: "databook", note: "Narutopedia: Part II 166 cm" },
  e_aoi: { kind: "human", p1: 182.5, source: "anime", note: "Narutopedia: Part I 182.5 cm (anime-only arc; figure from anime material, not a databook)" },
  e_bandit_ninja: { kind: "human", p2: 175, source: "estimate", note: "Generic adult rogue ninja" },
  e_c2_dragon: { kind: "giant", source: "estimate", note: "Deidara's C2 dragon" },
  e_clay_bird: { kind: "beast", p2: 150, source: "estimate", note: "Deidara's clay bird, sized like a person here; standing silhouette estimate" },
  e_crow_clone: { kind: "human", p2: 178, source: "estimate", note: "Crow Clone of Itachi: Itachi's Narutopedia Part II 178 cm" },
  e_danzo: { kind: "human", p2: 170, source: "databook", note: "Narutopedia: Danzo Shimura Part II 170 cm" },
  e_doki: { kind: "giant", source: "estimate", note: "Tayuya's Doki: ogre summons several times a person's height" },
  e_dosu: { kind: "human", p1: 156, source: "databook", note: "Narutopedia: Part I 156 cm" },
  e_foundation_op: { kind: "human", p2: 175, source: "estimate", note: "Generic adult Root operative" },
  e_four_tails: { kind: "giant", source: "estimate", note: "Tailed beast" },
  e_fudo: { kind: "human", p2: 195, source: "anime", note: "Narutopedia: Part II 195 cm (anime-only character; not a databook figure)" },
  e_fuka: { kind: "human", p2: 170, source: "anime", note: "Narutopedia: Part II 170 cm (anime-only character; not a databook figure)" },
  e_gato_thug: { kind: "human", p1: 175, source: "estimate", note: "Adult male hired thug; typical adult height" },
  e_giant_squid: { kind: "giant", source: "estimate", note: "Giant squid" },
  e_ginkaku: { kind: "human", p2: 177.9, source: "databook", note: "Narutopedia: Part II 177.9 cm" },
  e_gotta: { kind: "human", p2: 180, source: "anime", note: "Narutopedia: Part II 180 cm (anime-only character; not a databook figure)" },
  e_gozu: { kind: "human", p1: 178, source: "databook", note: "Narutopedia: Part I 178 cm" },
  e_guren: { kind: "human", p2: 168, source: "anime", note: "Narutopedia: Guren Part II 168 cm (anime-only character; not a databook figure)" },
  e_hashirama: { kind: "human", p1: 185.1, source: "databook", note: "Narutopedia: Hashirama Part II 185.1 cm (only figure), used for the Part I reanimation" },
  e_itachi_clone: { kind: "human", p2: 178, source: "estimate", note: "Shadow Clone of Itachi: Itachi's Narutopedia Part II 178 cm" },
  e_kagari: { kind: "human", p1: 168.8, source: "databook", note: "Narutopedia: Part I 168.8 cm" },
  e_kaguya: { kind: "human", p2: 172, source: "estimate", note: "No height on Narutopedia; tall adult woman as drawn in the anime" },
  e_kazuma: { kind: "human", p2: 186, source: "anime", note: "Narutopedia: Kazuma Part II 186 cm (anime-only character; not a databook figure)" },
  e_kigiri: { kind: "human", p2: 189.5, source: "anime", note: "Narutopedia: Part II 189.5 cm (anime-only character; not a databook figure)" },
  e_kin: { kind: "human", p1: 150, source: "databook", note: "Narutopedia: Part I 150 cm" },
  e_kinkaku: { kind: "human", p2: 183.9, source: "databook", note: "Narutopedia: Part II 183.9 cm" },
  e_kurosuki: { kind: "human", p1: 175, source: "estimate", note: "Generic adult Kurosuki Family thug (stocky man)" },
  e_manda: { kind: "giant", source: "estimate", note: "Giant snake summon" },
  e_masked_beast: { kind: "beast", p2: 250, source: "estimate", note: "Kakuzu's masked beasts are hulking thread creatures bigger than a man; standing silhouette estimate" },
  e_meizu: { kind: "human", p1: 178, source: "databook", note: "Narutopedia: Part I 178 cm" },
  e_misty_follower: { kind: "human", p2: 168, source: "estimate", note: "Generic Hidden Rain genin follower (teen/young adult ninja)" },
  e_misumi: { kind: "human", p1: 174.7, source: "databook", note: "Narutopedia: Part I 174.7 cm" },
  e_mizuki: { kind: "human", p2: 179.4, source: "databook", note: "Narutopedia: only Part I 179.4 cm; used for Part II" },
  e_mu: { kind: "human", p2: 173, source: "databook", note: "Narutopedia: Mu (Second Tsuchikage) Part II 173 cm" },
  e_mu_fragment: { kind: "human", p2: 173, source: "databook", note: "Narutopedia: Mu's Part II 173 cm" },
  e_mubi: { kind: "human", p1: 169.5, source: "databook", note: "Narutopedia: Part I 169.5 cm" },
  e_nine_tails: { kind: "giant", source: "estimate", note: "Tailed beast" },
  e_nurari: { kind: "human", p2: 183.5, source: "anime", note: "Narutopedia: Part II 183.5 cm (anime-only character; not a databook figure)" },
  e_oboro: { kind: "human", p1: 163.4, source: "databook", note: "Narutopedia: Part I 163.4 cm" },
  e_pain_animal: { kind: "human", p2: 168.5, source: "databook", note: "Narutopedia: First Animal Path (male Fuma clan body, matches the art prompt) Part II 168.5 cm; the female second Animal Path (Ajisai) is 155.6 cm" },
  e_pain_asura: { kind: "human", p2: 189, source: "databook", note: "Narutopedia: Asura Path (character) Part II 189 cm" },
  e_pain_naraka: { kind: "human", p2: 185, source: "databook", note: "Narutopedia: Naraka Path (character) Part II 185 cm" },
  e_pain_preta: { kind: "human", p2: 192, source: "databook", note: "Narutopedia: Preta Path (character) Part II 192 cm" },
  e_puppet: { kind: "human", p2: 178, source: "estimate", note: "One of Sasori's human puppets; adult-human height estimate" },
  e_raiga: { kind: "human", p1: 195, source: "anime", note: "Narutopedia: Part I 195 cm (anime-only character; not a databook figure)" },
  e_rain_ninja: { kind: "human", p2: 172, source: "estimate", note: "Generic adult Hidden Rain ninja" },
  e_ranmaru: { kind: "human", p1: 113, source: "anime", note: "Narutopedia: Part I 113 cm (anime-only character; not a databook figure)" },
  e_revived_soul: { kind: "human", p2: 172, source: "estimate", note: "Revived dead ninja of the Fire Temple arc; generic adult height" },
  e_sand_ninja: { kind: "human", p1: 172, source: "estimate", note: "Generic adult Sand shinobi" },
  e_shiranami: { kind: "human", p2: 180, source: "anime", note: "Narutopedia: Part II 180 cm (anime-only character; not a databook figure)" },
  e_smoke_clone: { kind: "human", p2: 172, source: "estimate", note: "Smoke clone of a generic ninja; generic adult height" },
  e_sora: { kind: "human", p2: 164, source: "anime", note: "Narutopedia: Part II 164 cm (anime-only character; not a databook figure)" },
  e_sound_ninja: { kind: "human", p1: 172, source: "estimate", note: "Generic adult Sound shinobi" },
  e_summoned_beast: { kind: "giant", source: "estimate", note: "Animal Path giant summons (rhino, dog, chameleon, centipede, etc.)" },
  e_ten_tails_clone: { kind: "beast", p2: 210, source: "estimate", note: "Ten-Tails clones are pale humanoid creatures a little taller than a man; standing silhouette estimate" },
  e_three_tails: { kind: "giant", source: "estimate", note: "Tailed beast" },
  e_tobi: { kind: "human", p2: 175, source: "databook", note: "Narutopedia: Obito Part II listed 175-182 cm; 175 (the masked Tobi-era figure) used" },
  e_tobirama: { kind: "human", p1: 182.3, source: "databook", note: "Narutopedia: Tobirama Part II 182.3 cm (only figure), used for the Part I reanimation" },
  e_tracker_ninja: { kind: "human", p2: 172, source: "estimate", note: "Generic adult Mist hunter-nin" },
  e_ukon: { kind: "human", p2: 155.1, source: "databook", note: "Narutopedia: Sakon and Ukon Part I 155.1 cm (only figure), used for Part II" },
  e_waraji: { kind: "human", p1: 181.4, source: "databook", note: "Narutopedia: Part I 181.4 cm" },
  e_water_clone: { kind: "human", p2: 183, source: "estimate", note: "Water Clone of Zabuza (per the game's art prompt): Zabuza's Narutopedia Part I 183 cm" },
  e_wood_clone: { kind: "human", p2: 178, source: "estimate", note: "Wood Clone of Yamato: Yamato's Narutopedia Part II 178 cm" },
  e_yoroi: { kind: "human", p1: 180, source: "databook", note: "Narutopedia: Part I 180 cm" },
  e_zaku: { kind: "human", p1: 157.3, source: "databook", note: "Narutopedia: Part I 157.3 cm" },
  e_zori: { kind: "human", p1: 172, source: "databook", note: "Narutopedia: Part I 172 cm" },
  gaara: { kind: "human", p1: 148.1, p2: 166.1, source: "databook", note: "Narutopedia: Part I 146.1-148.1 cm (later used), Part II 166.1 cm" },
  gaara_kazekage: { kind: "human", p2: 166.1, source: "databook", note: "Narutopedia: Gaara's Part II 166.1 cm" },
  guy: { kind: "human", p1: 184, p2: 184, source: "databook", note: "Narutopedia: only Part I 184 cm; used for both eras" },
  guy_eightgates: { kind: "human", p2: 184, source: "databook", note: "Narutopedia: Guy's only figure 184 cm (Part I), used for Part II" },
  haku: { kind: "human", p1: 155.9, source: "databook", note: "Narutopedia: Part I 155.9 cm" },
  hashirama: { kind: "human", p2: 185.1, source: "databook", note: "Narutopedia: Part II 185.1 cm" },
  hidan: { kind: "human", p2: 177.1, source: "databook", note: "Narutopedia: Part II 177.1 cm" },
  hinata: { kind: "human", p1: 148.3, p2: 160, source: "databook", note: "Narutopedia: Part I 147.3-148.3 cm (later used), Part II 160 cm" },
  hiruzen: { kind: "human", p1: 163.1, source: "databook", note: "Narutopedia: Part I 163.1 cm" },
  ino: { kind: "human", p1: 151.2, p2: 162.2, source: "databook", note: "Narutopedia: Part I 149.3-151.2 cm (later used), Part II 162.2 cm" },
  iruka: { kind: "human", p1: 178, p2: 178, source: "databook", note: "Narutopedia: only Part I 178 cm; used for both eras" },
  itachi: { kind: "human", p2: 178, source: "databook", note: "Narutopedia: Part I 175.2 cm, Part II 178 cm (Part II used)" },
  jiraiya: { kind: "human", p1: 191.2, p2: 191.2, source: "databook", note: "Narutopedia: only Part I 191.2 cm; used for both eras" },
  jirobo: { kind: "human", p1: 181.3, source: "databook", note: "Narutopedia: Part I 181.3 cm" },
  jugo: { kind: "human", p2: 202.1, source: "databook", note: "Narutopedia: Part II 202.1 cm" },
  kabuto: { kind: "human", p1: 176.2, p2: 177, source: "databook", note: "Narutopedia: Part I 176.2 cm, Part II 177 cm" },
  kakashi: { kind: "human", p1: 181, p2: 181, source: "databook", note: "Narutopedia: only Part I 181 cm; used for both eras" },
  kakashi_mangekyo: { kind: "human", p2: 181, source: "databook", note: "Narutopedia: Kakashi's only figure 181 cm (Part I), used for Part II" },
  kakuzu: { kind: "human", p2: 185, source: "databook", note: "Narutopedia: Part II 185 cm" },
  kankuro: { kind: "human", p1: 167, p2: 175, source: "databook", note: "Narutopedia: Part I 165-167 cm (later used), Part II 175 cm" },
  karin: { kind: "human", p2: 162.6, source: "databook", note: "Narutopedia: Part II 162.6 cm" },
  kiba: { kind: "human", p1: 152.5, p2: 169.1, source: "databook", note: "Narutopedia: Part I 151.2-152.5 cm (later used), Part II 169.1 cm" },
  kidomaru: { kind: "human", p1: 159.2, source: "databook", note: "Narutopedia: Part I 159.2 cm" },
  killer_bee: { kind: "human", p2: 192, source: "databook", note: "Narutopedia: Part II 192 cm" },
  kimimaro: { kind: "human", p1: 166.1, source: "databook", note: "Narutopedia: Part I 166.1 cm" },
  kisame: { kind: "human", p2: 195, source: "databook", note: "Narutopedia: only Part I 195 cm listed; used for Part II" },
  konan: { kind: "human", p2: 169.4, source: "databook", note: "Narutopedia: Part II 169.4 cm" },
  konohamaru: { kind: "human", p2: 141.1, source: "databook", note: "Narutopedia: Part II 141.1 cm" },
  kurenai: { kind: "human", p1: 169.1, p2: 169.1, source: "databook", note: "Narutopedia: only Part I 169.1 cm; used for both eras" },
  kurotsuchi: { kind: "human", p2: 163.6, source: "databook", note: "Narutopedia: Part II 163.6 cm" },
  lee: { kind: "human", p1: 162.1, p2: 172, source: "databook", note: "Narutopedia: Part I 158.5-162.1 cm (later used), Part II 172 cm" },
  madara: { kind: "human", p2: 179, source: "databook", note: "Narutopedia: Part II 179 cm" },
  mei: { kind: "human", p2: 174, source: "databook", note: "Narutopedia: Part II 174 cm" },
  minato: { kind: "human", p2: 179.2, source: "databook", note: "Narutopedia: only Part I 179.2 cm listed; used for Part II" },
  naruto: { kind: "human", p1: 147.5, p2: 166, source: "databook", note: "Narutopedia: Part I 145.3-147.5 cm (later used), Part II 166 cm" },
  naruto_chakramode: { kind: "human", p2: 166, source: "databook", note: "Narutopedia: Naruto's Part II 166 cm" },
  naruto_ninetails: { kind: "human", p1: 147.5, source: "databook", note: "Narutopedia: Naruto's Part I 145.3-147.5 cm (later used)" },
  naruto_sage: { kind: "human", p2: 166, source: "databook", note: "Narutopedia: Naruto's Part II 166 cm" },
  naruto_sixpaths: { kind: "human", p2: 166, source: "databook", note: "Narutopedia: Naruto's Part II 166 cm" },
  neji: { kind: "human", p1: 160.1, p2: 172.1, source: "databook", note: "Narutopedia: Part I 159.2-160.1 cm (later used), Part II 172.1 cm" },
  npc_hotaru: { kind: "human", p1: 153, source: "anime", note: "Narutopedia: Hotaru listed Part II 153 cm (anime-only Shippuden filler character), used for the Part I sprite" },
  npc_idate: { kind: "human", p1: 160, source: "estimate", note: "No height on Narutopedia; Idate is a young teenage runner in the Part I Land of Tea filler" },
  npc_leaf_villager: { kind: "human", p1: 165, source: "estimate", note: "Generic adult Leaf civilian" },
  npc_motoi: { kind: "human", p1: 177.1, source: "databook", note: "Narutopedia: Motoi (Hidden Cloud) listed Part II 177.1 cm, used for the Part I sprite" },
  npc_rokusuke: { kind: "human", p1: 165, source: "anime", note: "Narutopedia: Part I 165 cm (anime-only character; not a databook figure)" },
  npc_tazuna: { kind: "human", p1: 179, source: "databook", note: "Narutopedia: Part I 179 cm" },
  npc_tsunami: { kind: "human", p1: 158, source: "databook", note: "Narutopedia: Part I 158 cm" },
  obito: { kind: "human", p2: 182, source: "databook", note: "Narutopedia: Part I 154.2 cm, Part II 175-182 cm (182, the later figure, used)" },
  omoi: { kind: "human", p2: 170, source: "databook", note: "Narutopedia: Part II 170 cm" },
  onoki: { kind: "human", p2: 130, source: "databook", note: "Narutopedia: Part II 130 cm" },
  orochimaru: { kind: "human", p1: 179.4, p2: 172, source: "databook", note: "Narutopedia: Part I listed as 179.4-172 cm (179.4 used), Part II 172 cm; databooks disagree" },
  pain: { kind: "human", p2: 176.5, source: "databook", note: "Narutopedia: Yahiko (Deva Path body) Part II 176.5 cm; Nagato himself is 175.5 cm" },
  sai: { kind: "human", p2: 172.1, source: "databook", note: "Narutopedia: Part II 172.1 cm" },
  sakon: { kind: "human", p1: 155.1, source: "databook", note: "Narutopedia: Part I 155.1 cm (Sakon and Ukon)" },
  sakura: { kind: "human", p1: 150.1, p2: 161, source: "databook", note: "Narutopedia: Part I 148.5-150.1 cm (later used), Part II 161 cm" },
  sakura_hundred: { kind: "human", p2: 161, source: "databook", note: "Narutopedia: Sakura's Part II 161 cm" },
  sasori: { kind: "human", p2: 164.1, source: "databook", note: "Narutopedia: Part II 164.1 cm (his real body; Hiruko is larger)" },
  sasuke: { kind: "human", p1: 153.2, p2: 168, source: "databook", note: "Narutopedia: Part I 150.8-153.2 cm (later used), Part II 168 cm" },
  sasuke_cursemark: { kind: "human", p1: 153.2, source: "databook", note: "Narutopedia: Sasuke's Part I 150.8-153.2 cm (later used)" },
  sasuke_ems: { kind: "human", p2: 168, source: "databook", note: "Narutopedia: Sasuke's Part II 168 cm" },
  shikamaru: { kind: "human", p1: 152.1, p2: 170, source: "databook", note: "Narutopedia: Part I 150.8-152.1 cm (later used), Part II 170 cm" },
  shino: { kind: "human", p1: 161.1, p2: 175.1, source: "databook", note: "Narutopedia: Part I 156.2-161.1 cm (later used), Part II 175.1 cm" },
  shizune: { kind: "human", p1: 168, p2: 168, source: "databook", note: "Narutopedia: only Part I 168 cm; used for both eras" },
  suigetsu: { kind: "human", p2: 177.4, source: "databook", note: "Narutopedia: Part II 177.4 cm" },
  tayuya: { kind: "human", p1: 148.2, source: "databook", note: "Narutopedia: Part I 148.2 cm" },
  temari: { kind: "human", p1: 159.3, p2: 165, source: "databook", note: "Narutopedia: Part I 157.3-159.3 cm (later used), Part II 165 cm" },
  tenten: { kind: "human", p1: 155.6, p2: 164, source: "databook", note: "Narutopedia: Part I 154.3-155.6 cm (later used), Part II 164 cm" },
  tsunade: { kind: "human", p1: 163.1, p2: 163.1, source: "databook", note: "Narutopedia: Part I 163.1 cm, Part II 163.1 cm" },
  yamato: { kind: "human", p2: 178, source: "databook", note: "Narutopedia: Part II 178 cm" },
  zabuza: { kind: "human", p1: 183, source: "databook", note: "Narutopedia: Part I 183 cm" },
};
