// tools/naming.mjs — keeps NAMING.md in sync with the content files.
//   node tools/naming.mjs           # list names that have no recorded source
//   node tools/naming.mjs --write   # regenerate the tables between the markers in NAMING.md
//   node tools/naming.mjs --check   # exit 1 if any name has no source (used in CI-style checks)
// Sources live in tools/naming-sources.mjs.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { CONTENT as C } from '../js/content/index.js';
import { NAME_SOURCES as S, wikiUrl } from './naming-sources.mjs';

export function collectNames() {
  const uses = new Map();
  const add = (n, cat) => { if (!n) return; if (!uses.has(n)) uses.set(n, new Set()); uses.get(n).add(cat); };
  for (const c of C.roster) { add(c.name, 'character'); add(c.ult.name, 'jutsu'); }
  for (const e of C.enemies) { add(e.name, e.role === 'Civilian' ? 'character' : 'character'); if (e.jutsu) add(e.jutsu.name, 'jutsu'); for (const m of e.mechanics || []) add(m.name, 'jutsu'); }
  for (const a of C.arcs) { add(a.name, 'story'); for (const n of a.nodes || []) add(n.name, 'story'); }
  for (const b of C.banners) add(b.name, 'story');
  return uses;
}

export function missingNames() { return [...collectNames().keys()].filter(n => !S[n]); }

const LABEL = { V: 'Verified', P: 'Partly verified', D: 'Descriptive', N: '**NOT VERIFIED**' };
function usedAs(name) {
  const out = [];
  for (const c of C.roster) { if (c.name === name) out.push(`Pullable (${c.tier})`); if (c.ult.name === name) out.push(`Ult: ${c.short}`); }
  for (const e of C.enemies) {
    if (e.name === name && !out.includes(e.role === 'Civilian' ? 'Protect target' : 'Enemy')) out.push(e.role === 'Civilian' ? 'Protect target' : 'Enemy');
    if (e.jutsu?.name === name) out.push(`Jutsu: ${e.name}`);
    for (const m of e.mechanics || []) if (m.name === name) out.push(`${m.type}: ${e.name}`);
  }
  for (const a of C.arcs) { if (a.name === name) out.push(a.placeholder ? 'Part II placeholder' : 'Arc'); for (const n of a.nodes || []) if (n.name === name) out.push('Node'); }
  for (const b of C.banners) if (b.name === name) out.push('Banner');
  return [...new Set(out)].slice(0, 6).join('; ');
}
function table(names) {
  const rows = names.sort((a, b) => a.localeCompare(b)).map(n => {
    const s = S[n] || { page: null, status: 'N', note: 'No source recorded.' };
    return `| ${n} | ${usedAs(n)} | ${s.page ? `[${s.page}](${wikiUrl(s.page)})` : '—'} | ${LABEL[s.status]} | ${s.note || ''} |`;
  });
  return '| Name in game | Used as | Source checked | Status | Notes |\n|---|---|---|---|---|\n' + rows.join('\n') + '\n';
}

export function generateTables() {
  const uses = collectNames();
  const by = (cat) => [...uses.entries()].filter(([, c]) => c.has(cat)).map(([n]) => n);
  const chars = by('character');
  const jutsu = by('jutsu').filter(n => !chars.includes(n));
  const story = by('story').filter(n => !chars.includes(n) && !jutsu.includes(n));
  const notVerified = [...uses.keys()].filter(n => !S[n] || S[n].status === 'N');
  const partial = [...uses.keys()].filter(n => S[n]?.status === 'P');
  return [
    `_Generated by \`node tools/naming.mjs --write\` from the content files — ${uses.size} distinct names._\n`,
    `**Not verified:** ${notVerified.length ? notVerified.join(', ') : 'none'}.  `,
    `**Partly verified:** ${partial.length ? partial.join('; ') : 'none'}.\n`,
    '### Characters, enemies and protect targets\n', table(chars),
    '\n### Jutsu, Ultimates and boss-mechanic names\n', table(jutsu),
    '\n### Arcs, nodes and banners\n', table(story),
  ].join('\n');
}

const isMain = !!process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  const miss = missingNames();
  if (process.argv.includes('--write')) {
    const path = fileURLToPath(new URL('../NAMING.md', import.meta.url));
    const src = readFileSync(path, 'utf8');
    const next = src.replace(/<!-- NAMES:START -->[\s\S]*<!-- NAMES:END -->/, `<!-- NAMES:START -->\n${generateTables()}\n<!-- NAMES:END -->`);
    writeFileSync(path, next);
    console.log('NAMING.md tables regenerated.');
  }
  console.log(miss.length ? `${miss.length} name(s) without a source: ${miss.join(', ')}` : 'Every in-game name has a recorded source.');
  if (process.argv.includes('--check') && miss.length) process.exit(1);
}
